# Generated by Django 2.0 on 2019-03-20 15:49

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='static/images/background1.jpg', upload_to='static/avator/', verbose_name='头像'),
        ),
    ]
