# Generated by Django 2.0 on 2019-03-21 08:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_auto_20190320_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='static/images/background1.jpg', upload_to='avator/%Y%m%d/', verbose_name='头像'),
        ),
    ]
