# Generated by Django 2.0 on 2019-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190320_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='city',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='index',
            field=models.CharField(default=None, max_length=160),
        ),
        migrations.AlterField(
            model_name='blog',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='blog',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
