# Generated by Django 2.0 on 2019-03-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190320_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.ImageField(default='static/images/background1.jpg', upload_to='cover/%Y%m%d/'),
        ),
    ]
