# Generated by Django 2.0 on 2019-03-21 11:52

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Image',
        ),
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='static/images/background1.jpg', upload_to='cover/%Y%m%d/', verbose_name='头像'),
        ),
    ]
