# Generated by Django 2.0 on 2019-03-22 02:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190321_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='static/images/background1.jpg', upload_to='cover/%Y%m%d/', verbose_name='cover'),
        ),
    ]
